# 使用前先替换为你自己的配置
# replace conf when in use
HttpServerPort: 8089
AppSettings:
  AppCredentials:
    AppID: "app_id"
    AppSecret: "secret"
  AppEventKey:
    EnableEncrypt: true
    VerificationToken: "verifacation_token"
    EncryptKey: "encrypt_key"
  HelpDeskCredentials:
    EnableHelpDesk: false
    HelpDeskID: "help desk id"
    HelpDeskToken: "help desk token"