# 使用前先替换为你自己的配置
# replace conf when in use
HttpServerPort: 8089
AppSettings:
  AppCredentials:
    AppID: "cli_a6035948abf8d02e"
    AppSecret: "gvuCjuSl4gZVUVGpGSM08dPk4WuE5n4P"
  AppEventKey:
    EnableEncrypt: true
    VerificationToken: "BzZ5XV77Ud3wZTHIfOJj1gGo4gaZMYDz"
    EncryptKey: "zzu2p9RIsax9TSKHuISdzcF5fTRjXB4X"
  HelpDeskCredentials:
    EnableHelpDesk: false
    HelpDeskID: "help desk id"
    HelpDeskToken: "help desk token"